### ISSUE TITLE
What is the safe way to close a renderer test?

### ISSUE THREAD

**Issue by riatzukiza** [bokuweb/avaron#13]
I will run tests on a program, then when its over, avaron never closes.

I have a quit button in my program, I have tried
```js
test.always.after(async () => {click("#quit");})
```
And then I get:
```
Error: Object has been destroyed
    at Object.sendMessageToWindow [as sendToWindow] (/home/aaron/devel/contracts/jay-toy/thought-drop/client/node_modules/avaron/main/messages.js:6:9)
    at process.on.message (/home/aaron/devel/contracts/jay-toy/thought-drop/client/node_modules/avaron/main/initialize-renderer.js:24:12)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

  2 passed
  1 exception

  Uncaught Exception
  Error: Object has been destroyed
    Object.sendMessageToWindow [as sendToWindow] (node_modules/avaron/main/messages.js:6:9)
    process.on.message (node_modules/avaron/main/initialize-renderer.js:24:12)
Failed with exit code: 1
Output:

error Command failed with exit code 255.
```

**Comment by bokuweb** [comment]
@riatzukiza Thanks for your report. Could you please provide reproduced project if you get a chance?
